# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  haxe-build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          - windows-latest
        haxe:
          - latest
          - 4.3.3
          - 4.2.5
          - 4.1.5
        include:
          - lib_hxml: lib.hxml

    steps:
    - name: Show environment variables
      shell: bash
      run: env | sort

    - name: Git Checkout
      uses: actions/checkout@v2 #https://github.com/actions/checkout

    - name: Install Haxe ${{ matrix.haxe }}
      uses: krdlab/setup-haxe@v1.5.1 # https://github.com/krdlab/setup-haxe
      with:
        haxe-version: ${{ matrix.haxe }}
        cache-dependency-path: 'workflow/${{ matrix.lib_hxml }}''

    - name: Install haxe libs
      shell: bash
      id: prerequisites
      run: |
        haxelib install workflow/${{ matrix.lib_hxml }} --always
    
    - name: Test hxchart
      run: haxe tests.hxml
